// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	User
*/
package proto

import proto1 "github.com/golang/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal

type User struct {
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto1.CompactTextString(m) }
func (*User) ProtoMessage()    {}

type User_Login struct {
	Uuid          string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Host          string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	LoginType     int32  `protobuf:"varint,3,opt,name=login_type" json:"login_type,omitempty"`
	Cert          string `protobuf:"bytes,4,opt,name=cert" json:"cert,omitempty"`
	ClientVersion string `protobuf:"bytes,5,opt,name=client_version" json:"client_version,omitempty"`
	Lang          string `protobuf:"bytes,6,opt,name=lang" json:"lang,omitempty"`
	Appid         string `protobuf:"bytes,7,opt,name=appid" json:"appid,omitempty"`
	OsVersion     string `protobuf:"bytes,8,opt,name=os_version" json:"os_version,omitempty"`
	DeviceName    string `protobuf:"bytes,9,opt,name=device_name" json:"device_name,omitempty"`
	DeviceId      string `protobuf:"bytes,10,opt,name=device_id" json:"device_id,omitempty"`
	LoginIp       string `protobuf:"bytes,11,opt,name=login_ip" json:"login_ip,omitempty"`
}

func (m *User_Login) Reset()         { *m = User_Login{} }
func (m *User_Login) String() string { return proto1.CompactTextString(m) }
func (*User_Login) ProtoMessage()    {}

type User_Uid struct {
	Uid int32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *User_Uid) Reset()         { *m = User_Uid{} }
func (m *User_Uid) String() string { return proto1.CompactTextString(m) }
func (*User_Uid) ProtoMessage()    {}

type User_Auth struct {
	Uid     int32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Stats   int32 `protobuf:"varint,2,opt,name=stats" json:"stats,omitempty"`
	NewUser bool  `protobuf:"varint,3,opt,name=new_user" json:"new_user,omitempty"`
}

func (m *User_Auth) Reset()         { *m = User_Auth{} }
func (m *User_Auth) String() string { return proto1.CompactTextString(m) }
func (*User_Auth) ProtoMessage()    {}

type User_NullResult struct {
}

func (m *User_NullResult) Reset()         { *m = User_NullResult{} }
func (m *User_NullResult) String() string { return proto1.CompactTextString(m) }
func (*User_NullResult) ProtoMessage()    {}

func init() {
}

// Client API for LoginService service

type LoginServiceClient interface {
	Login(ctx context.Context, in *User_Login, opts ...grpc.CallOption) (*User_Auth, error)
	Logout(ctx context.Context, in *User_Uid, opts ...grpc.CallOption) (*User_Auth, error)
}

type loginServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoginServiceClient(cc *grpc.ClientConn) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) Login(ctx context.Context, in *User_Login, opts ...grpc.CallOption) (*User_Auth, error) {
	out := new(User_Auth)
	err := grpc.Invoke(ctx, "/proto.LoginService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) Logout(ctx context.Context, in *User_Uid, opts ...grpc.CallOption) (*User_Auth, error) {
	out := new(User_Auth)
	err := grpc.Invoke(ctx, "/proto.LoginService/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoginService service

type LoginServiceServer interface {
	Login(context.Context, *User_Login) (*User_Auth, error)
	Logout(context.Context, *User_Uid) (*User_Auth, error)
}

func RegisterLoginServiceServer(s *grpc.Server, srv LoginServiceServer) {
	s.RegisterService(&_LoginService_serviceDesc, srv)
}

func _LoginService_Login_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(User_Login)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(LoginServiceServer).Login(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _LoginService_Logout_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(User_Uid)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(LoginServiceServer).Logout(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _LoginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LoginService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _LoginService_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
