// Code generated by protoc-gen-go.
// source: default.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	default.proto

It has these top-level messages:
	SeedInfo
*/
package protos

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type SeedInfo struct {
	ClientSendSeed    int32 `protobuf:"varint,1,opt,name=client_send_seed" json:"client_send_seed,omitempty"`
	ClientReceiveSeed int32 `protobuf:"varint,2,opt,name=client_receive_seed" json:"client_receive_seed,omitempty"`
}

func (m *SeedInfo) Reset()         { *m = SeedInfo{} }
func (m *SeedInfo) String() string { return proto.CompactTextString(m) }
func (*SeedInfo) ProtoMessage()    {}

func init() {
}
